application:
  name: jordanQuartzApp2
datasource:
  jdbc-url: jdbc:oracle:thin:@localhost:1521:xe
  username: JORDANQUARTZ
  password: JORDANQUARTZ
  driver-class-name: oracle.jdbc.OracleDriver
quartz:
  job-store-type: jdbc

server:
  port: 8111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
    fetchRegistry: true
